export const gameCategories = [
  { value: "Abstract Strategy", name: "Abstract Strategy" },
  { value: "Adventure", name: "Adventure" },
  { value: "Area Control", name: "Area Control" },
  { value: "Campaign Legacy", name: "Campaign Legacy" },
  { value: "Card Games", name: "Card Games" },
  { value: "Cooperative", name: "Cooperative" },
  { value: "Deck Building", name: "Deck Building" },
  { value: "Dexterity", name: "Dexterity" },
  { value: "Dice Games", name: "Dice Games" },
  { value: "Drafting", name: "Drafting" },
  { value: "Economic", name: "Economic" },
  { value: "Educational", name: "Educational" },
  { value: "Engine Building", name: "Engine Building" },
  { value: "Eurogames", name: "Eurogames" },
  { value: "Family Games", name: "Family Games" },
  { value: "Fantasy", name: "Fantasy" },
  { value: "Horror", name: "Horror" },
  { value: "Humor", name: "Humor" },
  { value: "Miniatures", name: "Miniatures" },
  { value: "Mystery", name: "Mystery" },
  { value: "Mythology", name: "Mythology" },
  { value: "Party Games", name: "Party Games" },
  { value: "Puzzle", name: "Puzzle" },
  { value: "Racing", name: "Racing" },
  { value: "Role Playing", name: "Role Playing" },
  { value: "Sci-Fi", name: "Sci-Fi" },
  { value: "Strategy", name: "Strategy" },
  { value: "Thematic", name: "Thematic" },
  { value: "Tile Placement", name: "Tile Placement" },
  { value: "Trading", name: "Trading" },
  { value: "Trains", name: "Trains" },
  { value: "Word Games", name: "Word Games" },
];
