export const gameCategories = [
  { value: "Abstract Strategy", name: "Abstract Strategy" },
  { value: "Adventure", name: "Adventure" },
  { value: "Area Control", name: "Area Control" },
  { value: "Campaign/Legacy", name: "Campaign/Legacy" },
  { value: "Card Games", name: "Card Games" },
  { value: "Deck Building", name: "Deck-Building" },
  { value: "Dexterity", name: "Dexterity" },
  { value: "Dice Games", name: "Dice Games" },
  { value: "Drafting", name: "Drafting" },
  { value: "Economic", name: "Economic" },
  { value: "Educational", name: "Educational" },
  { value: "Engine Building", name: "Engine-Building" },
  { value: "Eurogames", name: "Eurogames" },
  { value: "Fantasy", name: "Fantasy" },
  { value: "Horror", name: "Horror" },
  { value: "Party Games", name: "Party Games" },
  { value: "Puzzle", name: "Puzzle" },
  { value: "Racing", name: "Racing" },
  { value: "Role-Playing", name: "Role-Playing" },
  { value: "Set Collection", name: "Set Collection" },
  { value: "Social Deduction", name: "Social Deduction" },
  { value: "Thematic", name: "Thematic" },
  { value: "Tile Laying", name: "Tile-Laying" },
  { value: "War Games", name: "War Games" },
  { value: "Worker Placement", name: "Worker Placement" },
];
